familiar_app/urls.py
from django.urls import path

from familiar_app import views

app_name = "familiar_app"
urlpatterns = [
    path("familiars", views.familiars, name="familiar-list"),
    path("familiar/add", views.create_familiar, name="familiar-add"),
]

family_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home_app.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("familiar_app/", include("familiar_app.urls")),
    path("neighbour_app/", include("neighbour_app.urls")),
    path("pet_app/", include("pet_app.urls")),
]

if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_app/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy


from home_app import views

app_name = "home_app"
urlpatterns = [
    path("", views.search, name="home"),
    path("about", views.about, name="about"),

    path('avatar/load', views.avatar_load, name='avatar-load'),
    path("accounts/signup", views.register, name="user-register"),
    path('accounts/profile/', views.user_update, name='user-update'),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/change-password.html',
            success_url=reverse_lazy("home_app:password-change-done")
        ),
        name="password-change"
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/change-password-done.html'
        ),
        name="password-change-done"
    ),
]

neighbour_app/urls.py
from django.urls import path

from neighbour_app import views

app_name = "neighbour_app"
urlpatterns = [
    path("neighbours", views.neighbours, name="neighbour-list"),
    path("neighbour/add", views.create_neighbour, name="neighbour-add"),
]

pet_app/urls.py
from django.urls import path

from pet_app import views

app_name = "pet_app"
urlpatterns = [
    #mascotas
    path("pets/", views.PetListView.as_view(), name="pet-list"),
    path("pet/add/", views.PetCreateView.as_view(), name="pet-add"),
    path("pet/<int:pk>/detail/", views.PetDetailView.as_view(), name="pet-detail"),
    path("pet/<int:pk>/update/", views.PetUpdateView.as_view(), name="pet-update"),
    path("pet/<int:pk>/delete/", views.PetDeleteView.as_view(), name="pet-delete"),

    #comentarios
    path("comment/<int:pk>/add/", views.CommentCreateView.as_view(), name="comment-create"),
    path("comment/<int:pk>/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
]

home_app/models.py
from django.contrib.auth.models import User
from django.db import models

class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='avatar', null=True, blank=True)

    def __str__(self):
        return f'user: {self.user.username} | url: {self.image.url}'

pet_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator

# Create your models here.
# class Pet(models.Model):
#     nombre = models.CharField(max_length = 80)
#     tipo = models.CharField(max_length = 50)
#     raza = models.CharField(max_length = 50)
#     edad = models.IntegerField()

#     def __str__(self) -> str:
#         return f"nombre: {self.nombre}, tipo: {self.tipo}, raza: {self.raza}, edad: {self.edad}"

class Pet(models.Model):
    titulo = models.CharField(max_length=40, null=False, blank=False)
    nombre = models.CharField(max_length=40, null=False, blank=False)
    descripcion = models.CharField(max_length=200, null=False, blank=False)
    imagen = models.ImageField(upload_to='pet', null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    comments = models.ManyToManyField(
        User, through="Comment", related_name="comments_owned"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (
            "titulo",
            "nombre",
        )
        ordering = ["-created_at"]

    def __str__(self):
        return f"Titulo: {self.titulo} | nombre: {self.nombre}"


class Comment(models.Model):
    text = models.TextField(
        validators=[
            MinLengthValidator(10, "El comentario debe ser mayor de 10 caracteres")
        ]
    )
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

home_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

from home_app.models import Avatar

class UserRegisterForm(UserCreationForm):

    username = forms.CharField(label="username", min_length=3)
    first_name = forms.CharField(label="Nombre", min_length=3)
    last_name = forms.CharField(label="Apellido", min_length=3)
    email = forms.EmailField(label="Correo electrónico")
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirmar Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]


class UserUpdateForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = [
            "email",
            "first_name",
            "last_name",
        ]
        widgets = {
            "email": forms.TextInput(attrs={"readonly": "readonly"}),
        }


class AvatarForm(forms.ModelForm):
    class Meta:
        model = Avatar
        fields = ("image", )
        

home_app/views.py
import os
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.forms.models import model_to_dict
from django.shortcuts import redirect
from django.shortcuts import render

from home_app.forms import AvatarForm
from home_app.forms import UserRegisterForm
from home_app.forms import UserUpdateForm
from home_app.models import Avatar

from pet_app.models import Pet


# Create your views here.
def search(request):
    context_dict = dict()
    if request.GET.get("search_param", False):
        search_param = request.GET["search_param"]
        if search_param:
            query = Q(titulo__contains=search_param)
            query.add(Q(nombre__contains=search_param), Q.OR)
            pet_list = Pet.objects.filter(query)
            context_dict.update(
                {
                    "pet_list": pet_list,
                    "search_param": search_param,
                }
            )
    return render(
        request=request,
        context=context_dict,
        template_name="home_app/home.html",
    )


def about(request):
    return render(
        request=request,
        template_name="home_app/about.html",
    )


def register(request):
    form = UserRegisterForm(request.POST) if request.POST else UserRegisterForm()
    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, "Usuario creado exitosamente!")
            return redirect("login")

    return render(
        request=request,
        context={"form": form},
        template_name="registration/register.html",
    )


@login_required
def user_update(request):
    user = request.user
    if request.method == "POST":
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("home_app:home")

    form = UserUpdateForm(model_to_dict(user))

    avatar_url = None
    avatars = Avatar.objects.filter(user=request.user.id)
    if avatars:
        avatar_url = avatars[0].image.url

    context = {"form": form, "avatar_url": avatar_url}
    return render(
        request=request,
        context=context,
        template_name="registration/user_form.html",
    )


@login_required
def avatar_load(request):
    if request.method == "POST":
        form = AvatarForm(request.POST, request.FILES)
        if form.is_valid and len(request.FILES) != 0:
            image = request.FILES["image"]
            avatars = Avatar.objects.filter(user=request.user.id)
            if not avatars.exists():
                avatar = Avatar(user=request.user, image=image)
            else:
                avatar = avatars[0]
                if len(avatar.image) > 0:
                    os.remove(avatar.image.path)
                avatar.image = image
            avatar.save()
            messages.success(request, "Imagen cargada exitosamente")
            return redirect("home_app:home")

    form = AvatarForm()
    return render(
        request=request,
        context={"form": form},
        template_name="home_app/avatar_form.html",
    )

home_app/templates/home_app/about.html
{% extends "home_app/index.html" %}
{% load static %}

{% block family_app_content %}
<div class="pt-3 text-center">
    
</div>
<br><br>
<center>
    <h2>Pet app</h2>
    Esta app es un blog enfocado en las publicaciones de las mascotas para
    que todos podamos ver lo grandiosas que son nuestros fieles compañeros.

    <hr class="my-3" />
    <h2>Acerca de mi</h2>
    <hr class="my-3" />
    <h3>
        Diana Sofia Tenorio
    </h3>
    <p>
        Estudiante de ingeniera industrial quinto semestre apasionada por 
        del deporte y en especial por el futbol, me gusta la música, 
        bailar y las mascotas
    </p>

    <hr class="my-3" />
    <h3>
        Andrés Felipe Toro
    </h3>
    <p>
        Estudiante de ingeniería industrial me gusta practicar 
        deporte y me gustan los animales, salir y conocer nuevos lugares
    </p>


</center>
<!-- Divider-->

{% endblock %}

home_app/templates/home_app/avatar_form.html
{% extends "home_app/index.html" %}
{% load static %}

{% block family_app_content %}
<h1>Cargar Avatar</h1>

    <h1>Usuario: {{user.username}} | {{user.first_name}} {{user.last_name}}</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Cargar Imagen</button>
    </form>
{% endblock %}

home_app/templates/home_app/home.html
{% extends "home_app/index.html" %}
{% load static %}

{% block family_app_content %}
<div class="pt-3 text-center">
    <h2>Busqueda de Mascotas</h2>
</div>
<br><br>
<div class="text-center">
    <!-- Buscador -->
    <form action="{% url 'home_app:home' %}" method="GET">
        <div>
            <input type="text" name="search_param" id="familiar" placeholder="Buscar.." {% if search_param %}
                value="{{ search_param }}" {% endif %}>
            <button class="btn btn-primary" type="submit">Buscar</button>
        </div>
    </form>
</div>
<!-- Divider-->
<hr class="my-5" />

<!-- Si hay resultados en el buscador los presenta -->
{% if pet_list %}
<div class="px-5">
    <ul class="list-group">
        {% for pet in pet_list %}
        <li class="list-group-item">
            <a class="text" href="{% url 'pet_app:pet-detail' pet.id %}">
                <h2>{{ pet.titulo }}</h2>
            </a>
            <h3>Mascota: {{ pet.nombre }}</h3>
            <p class="post-meta">
                Creado por
                <span style="color: #0b4956;" href="">{{ pet.owner.username }}</span>
                ( {{ pet.created_at }} )
            </p>
        </li>
        {% endfor %}
    </ul>
</div>
{% endif %}
</div>

{% endblock %}

home_app/templates/home_app/home.old.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Family App</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body>

    <div class="card w-75 mx-auto my-5">
        <div class="card-header text-center">
            MENU
        </div>
        <div class="card-body">

            <div class="row">
                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-body text-center">
                            <h5 class="card-title ">Visiatar listado de familiares</h5>
                            <p class="card-text">aquí se puede visualizar el listado de familiares
                            </p>
                            {% comment %} <a href="{% url 'familiar_app:familiar-list' %}" class="btn btn-primary">Ver familiares</a> {% endcomment %}
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-body text-center">
                            <h5 class="card-title">Panel de administración</h5>
                            <p class="card-text">
                                <b>Usuario:</b> sofiagt0413
                                <b>Clave:</b> 1234
                                <br>
                                En esta opción podrá registrar nuevos familiares / personas
                            </p>
                            <a href="{% url 'admin:index' %}" class="btn btn-primary">Panel</a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
        integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk"
        crossorigin="anonymous"></script>
</body>

</html>

home_app/templates/home_app/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Pet App</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home_app/css/template.css' %}" rel="stylesheet" />
    </head>
    <body>
        <div class="d-flex" id="wrapper">
            <!-- Sidebar-->
            <div class="border-end bg-white" id="sidebar-wrapper">
                <div class="sidebar-heading border-bottom bg-light">
                    <a href="{% url 'home_app:home' %}" class="text-decoration-none text-black text-center">
                        <h3>Pet App</h3>
                    </a>
                </div>
                <div class="list-group list-group-flush">
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'home_app:home' %}">Inicio</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'familiar_app:familiar-list' %}">Familiares</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'neighbour_app:neighbour-list' %}">Vecinos</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'pet_app:pet-list' %}">Mascotas</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'home_app:about' %}">Acerca de mí</a>
                </div>
            </div>
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                    <div class="container-fluid">
                        {% comment %} <button class="btn btn-primary" id="sidebarToggle">Menu</button> {% endcomment %}
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                                {% comment %} <li class="nav-item active"><a class="nav-link" href="#!">Iniciar</a></li> {% endcomment %}
                                {% if user.is_authenticated %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'home_app:user-update' %}">Editar usuario</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Cerrar Sesión - {{ user.username }}</a></li>
                                {% else %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Iniciar Sesión</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </nav>
                <!-- Page content-->
                <div class="container-fluid">

                    <!-- Messages-->
                    <div class="container position-relative px-4 px-lg-5">
                        <div class="row gx-4 gx-lg-5 justify-content-center">
                            <div class="col-md-10 col-lg-8 col-xl-7">
                                {% if messages %}
                                    {% for message in messages %}
                                        <div class="alert {{ message.tags }}" role="alert">
                                            {{ message }}
                                        </div>
                                    {% endfor %}
                                    <!-- Divider-->
                                    <hr class="my-4" />
                                {% endif %}
                            </div>
                        </div>
                    </div>
        
                    <div class="container-fluid py-3"> 
                        {% block family_app_content %}
                        {% endblock %}
                    </div>

                </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home_app/js/template.js' %}"></script>
    </body>
</html>