family_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home_app.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("familiar_app/", include("familiar_app.urls")),
    path("neighbour_app/", include("neighbour_app.urls")),
    path("pet_app/", include("pet_app.urls")),
]

if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet_app/urls.py
from django.urls import path

from pet_app import views

app_name = "pet_app"
urlpatterns = [
    #mascotas
    path("pets/", views.PetListView.as_view(), name="pet-list"),
    path("pet/add/", views.PetCreateView.as_view(), name="pet-add"),
    path("pet/<int:pk>/detail/", views.PetDetailView.as_view(), name="pet-detail"),
    path("pet/<int:pk>/update/", views.PetUpdateView.as_view(), name="pet-update"),
    path("pet/<int:pk>/delete/", views.PetDeleteView.as_view(), name="pet-delete"),

    #comentarios
    path("comment/<int:pk>/add/", views.CommentCreateView.as_view(), name="comment-create"),
    path("comment/<int:pk>/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
]

pet_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator

# Create your models here.
# class Pet(models.Model):
#     nombre = models.CharField(max_length = 80)
#     tipo = models.CharField(max_length = 50)
#     raza = models.CharField(max_length = 50)
#     edad = models.IntegerField()

#     def __str__(self) -> str:
#         return f"nombre: {self.nombre}, tipo: {self.tipo}, raza: {self.raza}, edad: {self.edad}"

class Pet(models.Model):
    titulo = models.CharField(max_length=40, null=False, blank=False)
    nombre = models.CharField(max_length=40, null=False, blank=False)
    descripcion = models.CharField(max_length=200, null=False, blank=False)
    imagen = models.ImageField(upload_to='pet', null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    comments = models.ManyToManyField(
        User, through="Comment", related_name="comments_owned"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (
            "titulo",
            "nombre",
        )
        ordering = ["-created_at"]

    def __str__(self):
        return f"Titulo: {self.titulo} | nombre: {self.nombre}"


class Comment(models.Model):
    text = models.TextField(
        validators=[
            MinLengthValidator(10, "El comentario debe ser mayor de 10 caracteres")
        ]
    )
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

pet_app/forms.py
from django import forms

from pet_app.models import Pet

# class petForm(forms.Form):

#     nombre = forms.CharField(
#         label="Nombre",
#         required=True,
#         widget=forms.TextInput(
#             attrs={
#                 "class": "form-control",
#                 "placeholder": "Nombre de la mascota",
#                 "required": "True",
#             }
#         ),
#     )

#     tipo = forms.ChoiceField(
#         label="Tipo",
#         required=True,
#         choices=[('perro','Perro'), ('gato','Gato'), ('tortuga', 'Tortuga'), ('loro','Loro'), ('otro', 'Otro')],
#         widget=forms.Select(
#             attrs={
#                 "class": "form-select",
#                 "placeholder": "tipo: perro, gato, loro....",
#                 "required": "True",
#             }
#         ),
#     )

#     raza = forms.CharField(
#         label="Raza",
#         required=True,
#         widget=forms.TextInput(
#             attrs={
#                 "class": "form-control",
#                 "placeholder": "Raza",
#                 "required": "True",
#             }
#         ),
#     )

#     edad = forms.IntegerField(
#         label="Edad",
#         required=True,
#         widget=forms.NumberInput(
#             attrs={
#                 "class": "form-control",
#                 "placeholder": "Edad",
#                 "required": "True",
#             }
#         ),
#     )


class PetForm(forms.ModelForm):

    imagen = forms.ImageField()

    titulo = forms.CharField(
        label="titulo del post",
        max_length=40,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "course-name",
                "placeholder": "titulo publicacion",
                "required": "True",
            }
        ),
    )

    nombre = forms.CharField(
        label="Nombre de la mascota",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "course-name",
                "placeholder": "Nombre de la mascota",
                "required": "True",
            }
        ),
    )

    descripcion = forms.CharField(
        label="Descripción:",
        required=False,
        widget=forms.Textarea(
            attrs={
                "required": "True",
            }
        ),
    )


    class Meta:
        model = Pet
        fields = ["titulo", "nombre", "descripcion", "imagen"]


class CommentForm(forms.Form):
    comment_text = forms.CharField(
        label="",
        required=False,
        max_length=500,
        min_length=10,
        strip=True,
        widget=forms.Textarea(
            attrs={
                "class": "comment-text",
                "placeholder": "Ingrese su comentario...",
                "required": "True",
                "max_length": 500,
                "min_length": 10,
                "rows": 2,
                "cols": 10,
                "style": "min-width: 100%",
            }
        ),
    )

pet_app/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from pet_app.models import Comment, Pet
from pet_app.forms import CommentForm, PetForm

class PetListView(ListView):
    model = Pet
    paginate_by = 3

class PetDetailView(DetailView):
    model = Pet
    template_name = "pet_app/pet_detail.html"
    fields = ["titulo", "nombre", "descripcion", "imagen"]
    
    def get(self, request, pk):
        pet = Pet.objects.get(id=pk)
        comments = Comment.objects.filter(pet=pet).order_by("-updated_at")
        comment_form = CommentForm()
        context = {
            "pet": pet,
            "comments": comments,
            "comment_form": comment_form,
        }
        return render(request, self.template_name, context)


class PetCreateView(LoginRequiredMixin, CreateView):
    model = Pet
    success_url = reverse_lazy("pet_app:pet-list")

    form_class = PetForm
    # fields = ["name", "code", "description", "image"]

    def form_valid(self, form):
        """Filter to avoid duplicate courses"""
        data = form.cleaned_data
        form.instance.owner = self.request.user
        actual_objects = Pet.objects.filter(
            titulo=data["titulo"], nombre=data["nombre"]
        ).count()
        if actual_objects:
            messages.error(
                self.request,
                f"La publicacion {data['titulo']} - de la mascota {data['nombre']} ya existe",
            )
            form.add_error("name", ValidationError("Acción no válida"))
            return super().form_invalid(form)
        else:
            messages.success(
                self.request,
                f"La publicacion {data['titulo']} - de la mascota {data['nombre']} ha sido creada exitosamente!",
            )
            return super().form_valid(form)


class PetUpdateView(LoginRequiredMixin, UpdateView):
    model = Pet
    form_class = PetForm
    #fields = ["titulo", "nombre", "descripcion", "imagen"]

    def get_success_url(self):
        pet_id = self.kwargs["pk"]
        return reverse_lazy("pet_app:pet-detail", kwargs={"pk": pet_id})

class PetDeleteView(LoginRequiredMixin, DeleteView):
    model = Pet
    success_url = reverse_lazy("pet_app:pet-list")


class CommentCreateView(LoginRequiredMixin, CreateView):
    def post(self, request, pk):
        pet = get_object_or_404(Pet, id=pk)
        comment = Comment(
            text=request.POST["comment_text"], owner=request.user, pet=pet
        )
        comment.save()
        return redirect(reverse("pet_app:pet-detail", kwargs={"pk": pk}))


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment

    def get_success_url(self):
        pet = self.object.pet
        return reverse("pet_app:pet-detail", kwargs={"pk": pet.id})

pet_app/templates/pet_app/comment_confirm_delete.html
{% extends "home_app/index.html" %}
{% load static %}

{% block family_app_content %}

<h3>Estás seguro de eliminar el comentario?</h3>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'pet_app:pet-detail' comment.pet.id %}" >Cancelar</a>
</form>

{% endblock %}

pet_app/templates/pet_app/pet-form.html
{% extends "home_app/index.html" %}
{% load static %}

{% block family_app_content %}

<div class="pt-3 text-center">
    <h2>Nueva mascota</h2>
    <br/>

    <div>
        <div class="card mx-auto" style="max-width: 30rem;">
            <div class="card-body">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-primary" value="Guardar" />
                </form>
            </div>
          </div>
    </div>


</div>
{% endblock %}

pet_app/templates/pet_app/pet_confirm_delete.html
{% extends "home_app/index.html" %}
{% load static %}

{% block family_app_content %}

<h3>Estás seguro de eliminar la publicación: {{pet.titulo}}?</h3>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'pet_app:pet-detail' pet.id %}" >Cancelar</a>
</form>

{% endblock %}

pet_app/templates/pet_app/pet_detail.html
{% extends "home_app/index.html" %}
{% load static %}

{% block family_app_content %}
<div class="container-fluid">
    <h2 class="text-center post-subtitle my-2">{{ pet.titulo }}</h2>

    {% if pet.imagen %}
    <div style="text-align: center;">
        <img height="250px" src="{{ pet.imagen.url }}">
    </div>
    {% endif %}

    <p class="card-text ">{{ pet.descripcion }}</p>

    <p class="post-meta">
        Creado por:
        <span style="color: #0b4956;" href="">{{ pet.owner.username }}</span>
        ( {{ pet.created_at }} )
        <br>
        Última fecha de actualización ( {{ pet.updated_at }} )
    </p>


    <!-- Update-Delete link only for the owner -->
    {% if user == pet.owner or user.is_superuser %}
    <a class="btn btn-success" href="{% url 'pet_app:pet-update' pet.id %}">Editar Publicación</a>
    <a class="btn btn-danger" href="{% url 'pet_app:pet-delete' pet.id %}">Eliminar Publicación</a>
    {% endif %}

    <!-- Divider-->

    <hr class="my-4" />
    <h4 class="text-center mb-5">Comentarios</h4>
    <!-- Comment creation -->
    {% if not comments %}
    <p class="text-center text-muted"> Sin Comentarios</p>
    {% endif %}

    <form method="POST" action="{% url 'pet_app:comment-create' pet.id %}">
        {% csrf_token %}
        {{ comment_form }}
        <input class="btn btn-primary" type="submit" value="Publicar comentario">
    </form>

    <!-- Comments list -->
    <ul class="list-group mt-5">
        {% for comment in comments %}
        <li class="list-group-item">
            <p> {{ comment.text }}
                <span class="text-muted">({{ comment.owner.username }} | {{ comment.updated_at }})</span>
                {% if user == comment.owner or user.is_superuser %}
                <a class="btn btn-danger" href="{% url 'pet_app:comment-delete' comment.id %}">Borrar</a>
                {% endif %}
            </p>
        </li>
        {% endfor %}
    </ul>

</div>
{% endblock %}

pet_app/templates/pet_app/pet_form.html
{% extends "home_app/index.html" %}
{% load static %}

{% block family_app_content %}

<div class="pt-3 text-center">
    <h2>Publicación de mascota</h2>
    <br/>

    <div>
        <div class="card mx-auto" style="max-width: 30rem;">
            <div class="card-body">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-primary" value="Guardar" />
                </form>
            </div>
          </div>
    </div>


</div>
{% endblock %}

pet_app/templates/pet_app/pet_list.html
{% extends "home_app/index.html" %}
{% load static %}

{% block family_app_content %}

<a class="btn btn-primary float-right" href="{% url 'pet_app:pet-add' %}">Crear nueva Publicación</a>
<br>

<div class="pt-3 text-center">
    <h2>Publicaciones de Mascotas</h2>
</div>

<br>

{% if pet_list %}{% else %}
<br>
<p class="text-center"><b>No hay publicaciones</b></p>
{% endif %}


<div class="px-5">
    <ul class="list-group">
        {% for pet in pet_list %}
        <li class="list-group-item">
            <a class="text" href="{% url 'pet_app:pet-detail' pet.id %}">
                <h2>{{ pet.titulo }}</h2>
            </a>
            <h3>Mascota: {{ pet.nombre }}</h3>
            <p class="post-meta">
                Creado por
                <span style="color: #0b4956;" href="">{{ pet.owner.username }}</span>
                ( {{ pet.created_at }} )
            </p>
        </li>
        {% endfor %}
    </ul>

    <!--Pagination Class Based Views-->
    {% if is_paginated %}
    <div class="container p-4">
        <div class="pagination justify-content-center">
            <span class="step-links">
                {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a> |
                <a href="?page={{ pet_list.previous_page_number }}">previous</a> |
                {% endif %}

                {% if page_obj.paginator.num_pages > 1 %}
                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} |
                </span>
                {% endif %}

                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a> |
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
    {% endif %}
    <!--end of Pagination-->
</div>

{% endblock %}