family_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home_app.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("familiar_app/", include("familiar_app.urls")),
    path("neighbour_app/", include("neighbour_app.urls")),
    path("pet_app/", include("pet_app.urls")),
]

if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

neighbour_app/urls.py
from django.urls import path

from neighbour_app import views

app_name = "neighbour_app"
urlpatterns = [
    path("neighbours", views.neighbours, name="neighbour-list"),
    path("neighbour/add", views.create_neighbour, name="neighbour-add"),
]

pet_app/urls.py
from django.urls import path

from pet_app import views

app_name = "pet_app"
urlpatterns = [
    #mascotas
    path("pets/", views.PetListView.as_view(), name="pet-list"),
    path("pet/add/", views.PetCreateView.as_view(), name="pet-add"),
    path("pet/<int:pk>/detail/", views.PetDetailView.as_view(), name="pet-detail"),
    path("pet/<int:pk>/update/", views.PetUpdateView.as_view(), name="pet-update"),
    path("pet/<int:pk>/delete/", views.PetDeleteView.as_view(), name="pet-delete"),

    #comentarios
    path("comment/<int:pk>/add/", views.CommentCreateView.as_view(), name="comment-create"),
    path("comment/<int:pk>/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
]

neighbour_app/models.py
from django.db import models

# Create your models here.
class Neighbour(models.Model):
    nombre = models.CharField(max_length = 80)
    barrio = models.CharField(max_length = 50)
    edad = models.IntegerField()

    def __str__(self) -> str:
        return f"nombre: {self.nombre}, barrio: {self.barrio}, edad: {self.edad}"

neighbour_app/forms.py
from django import forms

class neighbourForm(forms.Form):

    nombre = forms.CharField(
        label="Nombre",
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Nombre del vecino",
                "required": "True",
            }
        ),
    )

    barrio = forms.CharField(
        label="Barrio",
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Barrio donde vive",
                "required": "True",
            }
        ),
    )

    edad = forms.IntegerField(
        label="Edad",
        required=True,
        widget=forms.NumberInput(
            attrs={
                "class": "form-control",
                "placeholder": "Edad",
                "required": "True",
            }
        ),
    )

neighbour_app/views.py
from django.shortcuts import render
from django.contrib import messages
from neighbour_app.forms import neighbourForm
from neighbour_app.models import Neighbour
from django.contrib.auth.decorators import login_required

# Create your views here.
def neighbours(request):
    neighbour = Neighbour.objects.all()
    neighbours = {"neighbours": neighbour}
    return render(
        request=request,
        context=neighbours,
        template_name="neighbour_app/neighbour-list.html",
    )

@login_required
def create_neighbour(request):
    if request.method == "POST":
        neighbour_form = neighbourForm(request.POST)
        if neighbour_form.is_valid():
            data = neighbour_form.cleaned_data
            actual_objects = Neighbour.objects.filter(
                nombre=data["nombre"], barrio=data["barrio"]
            ).count()
            print("actual_objects", actual_objects)
            if actual_objects:
                messages.error(
                    request,
                    f"El vecino {data['nombre']} ya está creado",
                )
            else:
                course = Neighbour(
                    nombre=data["nombre"],
                    barrio=data["barrio"],
                    edad=data["edad"],
                    )
                course.save()
                messages.success(
                    request,
                    f"vecino {data['nombre']} creado exitosamente!",
                )

            neighbour = Neighbour.objects.all()
            neighbours = {"neighbours": neighbour}
            return render(
                request=request,
                context=neighbours,
                template_name="neighbour_app/neighbour-list.html",
            )

    neighbour_form = neighbourForm(request.POST)
    context_dict = {"form": neighbour_form}
    return render(
        request=request,
        context=context_dict,
        template_name="neighbour_app/neighbour-form.html",
    )

neighbour_app/templates/neighbour_app/neighbour-form.html
{% extends "home_app/index.html" %}
{% load static %}

{% block family_app_content %}

<div class="pt-3 text-center">
    <h2>Nuevo Vecino</h2>
    <br/>

    <div>
        <div class="card mx-auto" style="max-width: 30rem;">
            <div class="card-body">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-primary" value="Guardar" />
                </form>
            </div>
          </div>
    </div>


</div>
{% endblock %}

neighbour_app/templates/neighbour_app/neighbour-list.html
{% extends "home_app/index.html" %}
{% load static %}

{% block family_app_content %}

<a class="btn btn-primary float-right" href="{% url 'neighbour_app:neighbour-add' %}">Crear nuevo vecino</a>
<br>

<div class="pt-3 text-center">
    <h2>Lista de Vecinos</h2>
</div>

<br>
<div class="px-5">
    <ul class="list-group">
        {% for neighbour in neighbours %}
        <li class="list-group-item">
            <p class="h5"> <b>{{ neighbour.nombre }}</b> <br>
                <i>Barrio:</i> {{ neighbour.barrio }}
                <span class="mx-3"></span>
                <i>Edad: </i>{{ neighbour.edad }}
            </p>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}