familiar_app/urls.py
from django.urls import path

from familiar_app import views

app_name = "familiar_app"
urlpatterns = [
    path("familiars", views.familiars, name="familiar-list"),
    path("familiar/add", views.create_familiar, name="familiar-add"),
]

family_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home_app.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("familiar_app/", include("familiar_app.urls")),
    path("neighbour_app/", include("neighbour_app.urls")),
    path("pet_app/", include("pet_app.urls")),
]

if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet_app/urls.py
from django.urls import path

from pet_app import views

app_name = "pet_app"
urlpatterns = [
    #mascotas
    path("pets/", views.PetListView.as_view(), name="pet-list"),
    path("pet/add/", views.PetCreateView.as_view(), name="pet-add"),
    path("pet/<int:pk>/detail/", views.PetDetailView.as_view(), name="pet-detail"),
    path("pet/<int:pk>/update/", views.PetUpdateView.as_view(), name="pet-update"),
    path("pet/<int:pk>/delete/", views.PetDeleteView.as_view(), name="pet-delete"),

    #comentarios
    path("comment/<int:pk>/add/", views.CommentCreateView.as_view(), name="comment-create"),
    path("comment/<int:pk>/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
]

familiar_app/models.py
from django.db import models

# Create your models here.
class Familiar(models.Model):
    nombre = models.CharField(max_length = 80)
    altura = models.IntegerField()
    fecha_nacimiento = models.DateField()

    def __str__(self) -> str:
        return f"nombre: {self.nombre}, altura: {self.altura}, fecha de nacimiento: {self.fecha_nacimiento}"

familiar_app/forms.py
from django import forms


class FamiliarForm(forms.Form):

    nombre = forms.CharField(
        label="Nombre",
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Nombre del familiar",
                "required": "True",
            }
        ),
    )

    altura = forms.IntegerField(
        label="Altura:",
        required=True,
        widget=forms.NumberInput(
            attrs={
                "class": "form-control",
                "placeholder": "Altura en cm",
                "required": "True",
            }
        ),
    )

    fecha_nacimiento = forms.DateField(
        label="Fecha Nacimiento",
        required=True,
        widget=forms.DateInput(
            attrs={
                "type": "date",
                "class": "form-control",
                "required": "True",
            }
        )
    )

familiar_app/views.py
from django.shortcuts import render
from familiar_app.forms import FamiliarForm
from familiar_app.models import Familiar
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
def familiars(request):
    familiar = Familiar.objects.all()
    familiars = {"familiars": familiar}
    return render(
        request=request,
        context=familiars,
        template_name="familiar_app/familiar-list.html",
    )

@login_required
def create_familiar(request):
    if request.method == "POST":
        familiar_form = FamiliarForm(request.POST)
        if familiar_form.is_valid():
            data = familiar_form.cleaned_data
            actual_objects = Familiar.objects.filter(
                nombre=data["nombre"], fecha_nacimiento=data["fecha_nacimiento"]
            ).count()
            print("actual_objects", actual_objects)
            if actual_objects:
                messages.error(
                    request,
                    f"El Familiar {data['nombre']} ya está creado",
                )
            else:
                course = Familiar(
                    nombre=data["nombre"],
                    altura=data["altura"],
                    fecha_nacimiento=data["fecha_nacimiento"],
                    )
                course.save()
                messages.success(
                    request,
                    f"Familiar {data['nombre']} creado exitosamente!",
                )

            familiar = Familiar.objects.all()
            familiars = {"familiars": familiar}
            return render(
                request=request,
                context=familiars,
                template_name="familiar_app/familiar-list.html",
            )

    familiar_form = FamiliarForm(request.POST)
    context_dict = {"form": familiar_form}
    return render(
        request=request,
        context=context_dict,
        template_name="familiar_app/familiar-form.html",
    )

familiar_app/templates/familiar_app/familiar-form.html
{% extends "home_app/index.html" %}
{% load static %}

{% block family_app_content %}

<div class="pt-3 text-center">
    <h2>Nuevo de Familiar</h2>
    <br/>

    <div>
        <div class="card mx-auto" style="max-width: 30rem;">
            <div class="card-body">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-primary" value="Guardar" />
                </form>
            </div>
          </div>
    </div>


</div>
{% endblock %}

familiar_app/templates/familiar_app/familiar-list.html
{% extends "home_app/index.html" %}
{% load static %}

{% block family_app_content %}

<a class="btn btn-primary float-right" href="{% url 'familiar_app:familiar-add' %}">Crear nuevo Familiar</a>
<br>

<div class="pt-3 text-center">
    <h2>Lista de Familiares</h2>
</div>

<br>
<div class="px-5">
    <ul class="list-group">
        {% for familiar in familiars %}
        <li class="list-group-item">
            <p class="h5"> <b>{{ familiar.nombre }}</b> <br>
                <i>Altura:</i> {{ familiar.altura }}
                <span class="mx-3"></span>
                <i>Fecha de nacimiento: </i>{{ familiar.fecha_nacimiento }}
            </p>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}